### ISSUE TITLE
Window shows scrollbars in chrome

### ISSUE THREAD

**Issue by ghost** [quasarframework/app-template-default#11]
Hi,

when I create a quasar app with:
```bash
quasar init folder
cd folder
npm install
npm run dev
```

It shows scrollbars in Chrome, it does not when using Firefox.
When I resize the Chrome-window just by a pixel the scrollbars disappear and reappear on reload.

I just tried with MS Windows.

![image](https://cloud.githubusercontent.com/assets/3275348/22148933/4138554e-df11-11e6-9702-a89f92eccb72.png)

Do you have any idea how I could fix this behaviour?

Thank you very much
Regards
Seyhbold

**Comment by rstoenescu** [comment]
Hi, please use forum for questions. Yes, it's a Chrome extension causing this. Disable them one by one until you find the culprit. And please tell me which so we document this. Thanks!

**Comment by ghost** [comment]
Thank you for the quick response. Next time I'll use the forum first.

The extension causing this is WhatFont
https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm

**Comment by rstoenescu** [comment]
Thanks!
