### ISSUE TITLE
Grouping Components in the Same Chunk

### ISSUE THREAD

**Issue by Vaerum** [quasarframework/app-template-default#12]
Hi
I have problem grouping components in the same chunk by using the lazy loading from https://router.vuejs.org/en/advanced/lazy-loading.html. I believe it is something about the builder, but cannot find the problem. It does not work when using **children**. The URL shows up, but the content doesn't.

Ex.
```
File: routes.js

const Foo = r => require.ensure([], () => r(require('./Foo.vue')), 'group-foo')
const Bar = r => require.ensure([], () => r(require('./Bar.vue')), 'group-foo')

const routes = new VueRouter({
// WORKING EXAMPLE
  {
    path: '/',
    component: Foo
  },
// NOT WORKING EXAMPLE
  {
    path: '/',
    component: Foo,
    children: [
      {
        path: 'test',
        component: Bar
      }
    ]
  },
]

```
Any suggestions?

//Rasmus

**Comment by rstoenescu** [comment]
Hi, please use forum for questions. Use the "load()" function defined in the starter kit ;)
