### ISSUE TITLE
eslint Standard now applies an 'import' rule that conflicts with Main.js import order

### ISSUE THREAD

**Issue by dobromir-hristov** [quasarframework/app-template-default#18]
Eslint's Standard config applies the eslint-import validator which has a rule for imports where you should have your import statements above require statements, that conflicted with my `main.js` where the style require is above quasar's. I resolved this by adding:
```js
    'import/first': 0
``` 
to my `.eslintrc.js` file
Should I PR this, or has this occurred only on my end?

**Comment by smolinari** [comment]
This isn't normal behavior, AFAIK.

Do you by chance have the "eslint-plugin-import" plugin installed?

Scott

**Comment by rstoenescu** [comment]
Hi,

You may have upgraded ESLint in package.json too to a newer version which brings breaking changes. As a result you as a developer are responsible to make the necessary changes according to those breaking changes.

v0.14 starter kit will provide the newer ESLint version along with all necessary updates for it. Indeed the change you mentioned is required for the new ESLint to work, along with installing additional npm packages like `eslint-plugin-import`.

No need for a PR for current starter kit as it will become obsolete once v0.14 is released.

**Comment by dobromir-hristov** [comment]
Yep, I did an npm update yesterday and I had to install the aforementioned plugins manually.

**Comment by rstoenescu** [comment]
Updated all deps on current starter kit for v0.13 as well. To eliminate any confusion when npm updating.
