### ISSUE TITLE
Why Root component doesn't wraps all components?

### ISSUE THREAD

**Issue by aliuygur** [quasarframework/app-template-default#20]
Hello, I can't set data in root component. The root component doesn't wraps all components.

there is main.js

```js
Vue.use(Quasar) // Install Quasar Framework

Quasar.start(() => {
  /* eslint-disable no-new */
  new Vue({
    el: '#q-app',
    data () {
      return {name: 'ali'}
    },
    router,
    render: h => h(require('./App'))
  })
})
```

there is ss

![quasar](https://cloud.githubusercontent.com/assets/628322/25847954/f3bdcba4-34c0-11e7-8ef6-04970a6d18d9.png)

**Comment by rstoenescu** [comment]
`<Root>` is used for something else.
Your root component of your app is `<App>`. That is also the place you should inject data if you want to. So in App.vue, not in main.js

**Comment by aliuygur** [comment]
when i type `this.$root` this referencing the main.js  not the App.vue ?

**Comment by smolinari** [comment]
In the future, questions like this will get better attention in the forum or the chat, as was suggested in the new issue template. 

http://forum.quasar-framework.org/
https://gitter.im/quasarframework/Lobby

Please only use the repo to report bugs or improvement suggestions. 

Scott
