### ISSUE TITLE
IE Edge does not support vmax as font unit size

### ISSUE THREAD

**Issue by jclijmans** [quasarframework/app-template-default#28]
### Software version

Quasar: 0.14 beta
OS: windows 10
Node: 8.1.3
NPM: 5.0.4
Browsers: IE Edge
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Wrong font size for "404" text on Error404 page 
### What steps did you take, to get the error?
Started with a new project using the default template.
Navigated to an unknow url.
On IE Edge the "404" text in the Error404 component is displayed in the default font size.

As a workaround I've changed the style in the Error404.vue file to this for the fontsize :

    @media (orientation: landscape) { 
      font-size 30vw
    }
    @media (orientation: portrait) { 
      font-size 30vh
    }

This seems to work.

**Comment by rstoenescu** [comment]
Hi, care for a PR? Thanks for reporting this.

**Comment by jclijmans** [comment]
OK, should I create a pull request for master or edge?

**Comment by rstoenescu** [comment]
Both if your time allows it. "beta" (edge) branch is more important as it will soon become the default one, so that's a priority over any other.
