### ISSUE TITLE
[Request] - TypeScript - Integrate linting into vue-loader

### ISSUE THREAD

**Issue by Jackson3195** [quasarframework/app-template-default#34]
## Feature request

Would it be possible to incorporate the `ts-loader` & `tslint-loader` into the `vue-loader` for the quasar typescript template?
I'm relatively new to webpack and still actively learning but I managed to create my own template for the TypeScript library [Vuety](https://github.com/strantr/vuety). If my understanding is correct, all I did was switch `vue-class-component` for `vuety` thus I'd imagine this working for both. In the template, I managed to add linting for single file '*.vue' files, such that when the user compiles the component, it provides linting in the console. This will allow users to create single file '*.vue' files without the need to have a '*.ts' file imported into each component.
**Screenshot examples:**
_Screenshot of App.vue (Notice: `import HelloComponent from './components/Hello.vue'`)_
<img width="402" alt="screen shot 2017-07-17 at 22 50 47" src="https://user-images.githubusercontent.com/11081409/28292019-316e8780-6b45-11e7-9c74-2e40531cfec3.png">
_Screenshot of console running in dev, providing linting warnings/errors._
![screen shot 2017-07-17 at 22 50 36](https://user-images.githubusercontent.com/11081409/28292040-53f851b4-6b45-11e7-83bb-6437cdf286fd.png)

An argument can be made that developing in the '.ts' file provides real-time linting which is far more beneficial but I guess it's down to personal taste?
I have attempted to add both loaders to the `webpack.base.config.js` but to no avail, resulting in many errors/issues thus I am unsure how to integrate the loaders into the existing template.
**What mine look's like:**
<img width="395" alt="screen shot 2017-07-17 at 22 51 04" src="https://user-images.githubusercontent.com/11081409/28292161-c4ce2486-6b45-11e7-95f6-19e98a6dfcd5.png">
**What the template's look's like:**
<img width="387" alt="screen shot 2017-07-17 at 23 12 58" src="https://user-images.githubusercontent.com/11081409/28292184-d6f9e0c8-6b45-11e7-8a6a-b56ab260bba2.png">
**EDIT: Example of what I attempted**
<img width="579" alt="screen shot 2017-07-19 at 13 34 41" src="https://user-images.githubusercontent.com/11081409/28367053-254d20ae-6c87-11e7-9f2f-1dad1c740459.png">

**Comment by jclijmans** [comment]
This works 

      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          esModule: true,
          postcss: cssUtils.postcss,
          loaders: merge(cssUtils.styleLoaders({
            sourceMap: useCssSourceMap,
            extract: env.prod
          }), {ts: 'ts-loader!tslint-loader'})
        }
      },
