### ISSUE TITLE
Getting error when starting with quasar for first time

### ISSUE THREAD

**Issue by aswinkp** [quasarframework/app-template-default#46]
I just updated quasar-cli, and ran the three commands as mentioned in getting started section.

```
quasar init default app_name
cd app_name
npm install
quasar dev
```

localhost:8080 opens, but unfortunately, it says `Cannot GET /`

and console reads

 ```ERROR  Failed to compile with 1 errors                              10:24:20 AM
error  in ./src/App.vue
Syntax Error: Unexpected token {
 @ ./src/main.js 23:15-31
 @ multi ./build/hot-reload.js ./src/main.js
```
I neither opened the editor nor edited any file. So this should be an issue from starter kit.

vue 2.3.4
quasar-framework 0.14.4

**Comment by rstoenescu** [comment]
Hi,

Cannot reproduce this. What is your environment (OS and version, nodejs version, npm version, terminal, any other relevant tools that you use)?

**Comment by aswinkp** [comment]
@rstoenescu Ubuntu 16.04, npm 4.4.1, node 4.2.6

 I just created another project with  `quasar init default#v0.13 app_name` . It works without any issues. 

But not working when started with 0.14 template

**Comment by rstoenescu** [comment]
http://forum.quasar-framework.org/topic/972/solved-failed-to-compile-with-1-errors
Upgrade nodejs to at least v6 (latest LTS). For better performance I also recommend upgrading npm to its latest 5.x version.

**Comment by aswinkp** [comment]
@rstoenescu Thanks. That was totally unexpected. Atleast the error message should tell to update node version.

Maybe it would be great if the below lines were included in Getting Started docs.
```
node -v
//check if the version is greater than x.x.x
```

**Comment by rstoenescu** [comment]
The v0.15 starter kit will auto-check if nodejs and npm versions are right. Thanks for reporting this!
