### ISSUE TITLE
_h is not defined

### ISSUE THREAD

**Issue by vijaythecoder** [quasarframework/app-template-default#5]
I have recently switched my Vue SPA, it worked fine till morning and suddenly I see error. 
`ReferenceError: _h is not defined`

if I remove Quasar from `main.js`, it works but if I include Quasar, it throws me error. Any help would be highly appreciated.

**Comment by rstoenescu** [comment]
Can you tell me if Quasar v0.10 with Vue 2.1.4 (not 2.1.5+) works? Thanks!
It's a problem with rollup & rollup-plugin-vue compilers.

**Comment by vijaythecoder** [comment]
I am using vue 2.1.3 when I posted the error, I did try 2.1.4 and it kind of solves the problem. I mean it is not preventing to load the page but it throws errors 

```
(unknown) [Vue warn]: Property or method "_c" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

**Comment by vijaythecoder** [comment]
and `vue 2.1.6` throws the same error `ReferenceError: _h is not defined`

**Comment by rstoenescu** [comment]
Are you using Quasar v0.10.0 or v0.10.2?

**Comment by vijaythecoder** [comment]
This error is not because Quasar, sorry for that. Hope to see this framework work in latest :) 
```
Property or method "_c" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

I am using `quasar-framework": "^0.10.2"`

**Comment by rstoenescu** [comment]
Please try using Quasar 0.10.0 with Vue <= 2.1.4 and tell me if you still get these errors. Thanks!

**Comment by vijaythecoder** [comment]
yes I still have the errors after using 
```
"vue": "^2.1.4",
"quasar-framework": "^0.10.0",
```

**Comment by rstoenescu** [comment]
Released v0.10.3 (which is v0.10.2 repackaged). Please npm update to it and give it a try. Thanks!

**Comment by vijaythecoder** [comment]
`"quasar-framework": "^0.10.3"` works with `"vue": "^2.1.6"`, thanks a lot for the quick release and awesome response.

**Comment by vijaythecoder** [comment]
just sent you `$20` , I know its not big but happy to give something back. Thanks once again

**Comment by rstoenescu** [comment]
Wow! Thank you! And not just for the donation. For reporting this!

Did you by chance work(ed) for DCT/IBM or is it just a name coincidence?

**Comment by vijaythecoder** [comment]
I didn't get you which name? Nope I never worked. Freelancer from start.

**Comment by rstoenescu** [comment]
Worked with another Vijay Kumar some years ago. Thought it was you :)
