### ISSUE TITLE
Quasar is not working when run "quasar dev" with error quasar-app@0.0.1 dev: `node build/script.dev.js`

### ISSUE THREAD

**Issue by Vongsi** [quasarframework/app-template-default#52]
Dear All

Firstly, thanks for the creator and all contributors for this great Framework

This is my first time to install quasar but I got below error message, could you please advise.

# Below are software versions.

Quasar: ^0.14.4
OS: Windows 7
node: V6.11.2
npm: v5.5.1
"vue": "^2.5.0",
"vue-router": "^3.0.1"

# After installed Quasar
- I run "quasar dev" but nothing happened.
- then I run "npm run dev" and got below error message.

# And below are the error message from the log file

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Vongsi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.5.1
3 info using node@v6.11.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle quasar-app@0.0.1~predev: quasar-app@0.0.1
6 info lifecycle quasar-app@0.0.1~dev: quasar-app@0.0.1
7 verbose lifecycle quasar-app@0.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle quasar-app@0.0.1~dev: PATH: C:\Users\Vongsi\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\wamp64\www\quasar_using\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;D:\wamp64\bin\php\php7.0.10;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Windows\System32;C:\Users\Vongsi\AppData\Roaming\Composer\vendor\bin;C:\Users\Vongsi\AppData\Roaming\npm;C:\Users\Vongsi\AppData\Local\GitHubDesktop\bin;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle quasar-app@0.0.1~dev: CWD: D:\wamp64\www\quasar_using
10 silly lifecycle quasar-app@0.0.1~dev: Args: [ '/d /s /c', 'node build/script.dev.js' ]
11 silly lifecycle quasar-app@0.0.1~dev: Returned: code: 1  signal: null
12 info lifecycle quasar-app@0.0.1~dev: Failed to exec dev script
13 verbose stack Error: quasar-app@0.0.1 dev: `node build/script.dev.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Vongsi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Vongsi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid quasar-app@0.0.1
15 verbose cwd D:\wamp64\www\quasar_using
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vongsi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v6.11.2
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error quasar-app@0.0.1 dev: `node build/script.dev.js`
22 error Exit status 1
23 error Failed at the quasar-app@0.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Appreciated for your advise and help.

**Comment by rstoenescu** [comment]
~~It's not ready yet for public testing. Needs some symbolic links to work. Will be released along v0.15. Thanks for your patience.~~

edit: Misread and thought it was about some other repo.

**Comment by pdanpdan** [comment]
Hello. A step by step procedure would be:
- npm -g install quasar-cli
- quasar init <app_name>
- cd <app_name>
- npm install
- npm run dev

Are you trying to use the quasar-cli or the new, WIP, app?
Can you provide the steps you took till now?

**Comment by Vongsi** [comment]
Hi pdanpdan

Yes, I am using quasar-cli.

I have followed the steps on getting started page -> http://quasar-framework.org/guide/index.html

Below are steps I followed to install Quasar CLI and Quasar
$ npm install -g quasar-cli
$ quasar init default <folder_name>
$ cd <folder_name>
$ npm install
$ quasar dev -> at this step nothing happened,
then I try to run npm run dev -> when run this step I got above error message.

I have tried to delete the folder <folder_name> created above and follow steps at -> https://github.com/quasarframework/quasar-template-default

but also got the same error.

Thanks

**Comment by asifm** [comment]
@Vongsi Have you been able to solve the problem? If so, please report how you did that so that the issue can be closed. If not, have tried completely uninstalling npm and quasar-cli and then  reinstalling them?

**Comment by Vongsi** [comment]
Thanks @asifm , I did not have time to tried it again, but I just close it for now and will try again latter.
