### ISSUE TITLE
Property or method "_c" is not defined

### ISSUE THREAD

**Issue by Christilut** [quasarframework/app-template-default#6]
Getting alot of these warnings:
```
vue.runtime.common.js?d43f:509[Vue warn]: Property or method "_c" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in anonymous component at /home/user/workspace/quasar-app/src/App.vue)
```

Seems to happen once for every vue component that is being rendered.

Not really a breaking bug since everything seems to work fine but should probably be fixed.

**Comment by rstoenescu** [comment]
Rollup-plugin-vue compiler issue already solved. Use Quasar v0.10.3 with Vue 2.1.6. Thanks!
